#!/bin/bash

trap "exit" INT TERM
# try to terminate all child processes, wait 2 seconds, kill all child processes
trap "pkill -P $$; sleep 2; pkill --signal SIGKILL -P $$" EXIT

# command to launch the Tango Server
# launch Tango Server in background (don't forget & at the end of the line) !!

cd /home/user/bin/TangoServers/SpinMotors
python Spin_motors.py i0 &

while true; do sleep 3600; done
