#!/usr/bin/env python
# -*- coding:utf-8 -*-


# ############################################################################
#  license :
# ============================================================================
#
#  File :        Spin_motors.py
#
#  Project :     spin_motors
#
# This file is part of Tango device class.
# 
# Tango is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Tango is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Tango.  If not, see <http://www.gnu.org/licenses/>.
# 
#
#  $Author :      sergey.v.babenkov$
#
#  $Revision :    $
#
#  $Date :        $
#
#  $HeadUrl :     $
# ============================================================================
#            This file is generated by POGO
#     (Program Obviously used to Generate tango Object)
# ############################################################################

__all__ = ["Spin_motors", "Spin_motorsClass", "main"]

__docformat__ = 'restructuredtext'

import PyTango
import sys
# Add additional import
#----- PROTECTED REGION ID(Spin_motors.additionnal_import) ENABLED START -----#
import socket
import time
import threading
from threading import RLock
import os
import Tkinter as tk
import tkMessageBox

if sys.version_info[0] == 2:
    import ConfigParser as configparser
else:
    import configparser
from ipaddress import ip_address

from pylink import TCPLink
MOTORS = {
    "X":"0",
    "Y":"1",
    "Z":"2",
    "PHI":"3",
    "THETA":"4"
}
_MOTORS = {
    0:"X",
    1:"Y",
    2:"Z",
    3:"PHI",
    4:"THETA"
}
WAIT_TIME_UNIT=0.01
READ_SIZE=4096
TIMEOUT=0.1
#----- PROTECTED REGION END -----#	//	Spin_motors.additionnal_import

# Device States Description
# No states for this device


class Spin_motors (PyTango.Device_4Impl):
    """spin_motors"""
    
    # -------- Add you global variables here --------------------------
    #----- PROTECTED REGION ID(Spin_motors.global_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	Spin_motors.global_variables

    def __init__(self, cl, name):
        PyTango.Device_4Impl.__init__(self,cl,name)
        self.debug_stream("In __init__()")
        Spin_motors.init_device(self)
        #----- PROTECTED REGION ID(Spin_motors.__init__) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	Spin_motors.__init__
        
    def delete_device(self):
        self.debug_stream("In delete_device()")
        #----- PROTECTED REGION ID(Spin_motors.delete_device) ENABLED START -----#
        #----- PROTECTED REGION END -----#	//	Spin_motors.delete_device

    def init_device(self):
        self.debug_stream("In init_device()")
        self.get_device_properties(self.get_device_class())
        self.attr_PosZ_read = 0.0
        self.attr_insert_z_pos_read = 0.0
        self.attr_retract_z_pos_read = 0.0
        self.attr_positive_limit_z_read = False
        self.attr_negative_limit_z_read = False
        self.attr_PosX_read = 0.0
        self.attr_positive_limit_XY_read = False
        self.attr_negative_limit_XY_read = False
        self.attr_PosY_read = 0.0
        self.attr_motor_x_action_read = False
        self.attr_motor_y_action_read = False
        self.attr_motor_z_action_read = False
        self.attr_motor_phi_action_read = False
        self.attr_motor_theta_action_read = False
        #----- PROTECTED REGION ID(Spin_motors.init_device) ENABLED START -----#
        self.action=[False for _ in range(4)]
        self.device_id=[]
        self.connect_via_ethernet=False
        self.connect_via_serial=False
        self.PosZ_warning=False
        self.connection_warning=False
        self.interface_warning=False
        self.config_file_warning=False        
        
        self.port_busy=False
        self.config = configparser.ConfigParser()
        
 
        #           axis Z
        self._insert=False
        self._retract=False
        self.stepZ=0.0
        self.limitZpos=300.0
        self.limitZneg=0.0
        self.insertZ=0.0
        self.retractZ=0.0



        self.connected = False         
        self.last_comm_timeout=False
        self.WAIT_TIME_UNIT=0.01 
        self.commlock = RLock()
        self.pos=[0.0 for _ in range(4)]
        
        self.set_posX=0.0
        self.set_posY=0.0
        self.set_posZ=0.0
        self.set_posAngle=0.0
        
        self.stepX=0.0
        self.stepY=0.0
        self.stepAngle=0.0
        
        self.limitXYpos=10#12.5
        self.limitXYneg=-10#-12.5
        
        
        self.limitApos=300.0
        self.limitAneg=0.0

        
        
        if not 'poolthread' in dir(self):
            self.poolthread = threading.Thread(target=self.pool_motor_variables)
            self.poolthread.setDaemon(True)
            self.poolthread.start()
        if not 'AskQuestion' in dir(self):
            self.AskQuestion = threading.Thread(target=self.AskQuestion_thread)
            self.AskQuestion.setDaemon(True)
            self.AskQuestion.start() 
        self.config_check()
        #----- PROTECTED REGION END -----#	//	Spin_motors.init_device

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")
        #----- PROTECTED REGION ID(Spin_motors.always_executed_hook) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	Spin_motors.always_executed_hook

    # -------------------------------------------------------------------------
    #    Spin_motors read/write attribute methods
    # -------------------------------------------------------------------------
    
    def read_PosZ(self, attr):
        self.debug_stream("In read_PosZ()")
        #----- PROTECTED REGION ID(Spin_motors.PosZ_read) ENABLED START -----#
        attr.set_value(self.attr_PosZ_read)
        
        #----- PROTECTED REGION END -----#	//	Spin_motors.PosZ_read
        
    def write_StepZ(self, attr):
        self.debug_stream("In write_StepZ()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(Spin_motors.StepZ_write) ENABLED START -----#
        self.stepZ=data
        self.config.set('motor_Z', "step", data)
        #----- PROTECTED REGION END -----#	//	Spin_motors.StepZ_write
        
    def write_SpeedZ(self, attr):
        self.debug_stream("In write_SpeedZ()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(Spin_motors.SpeedZ_write) ENABLED START -----#
        if self.get_state() == PyTango.DevState.ON:
            self.write("@{} VR={}".format(MOTORS["Z"],str(data)))
            self.config.set('motor_Z', "speed", data)
        else:
            self.connection_warning=True
        #----- PROTECTED REGION END -----#	//	Spin_motors.SpeedZ_write
        
    def write_StopZ(self, attr):
        self.debug_stream("In write_StopZ()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(Spin_motors.StopZ_write) ENABLED START -----#
      
        #----- PROTECTED REGION END -----#	//	Spin_motors.StopZ_write
        
    def write_SetPosZ(self, attr):
        self.debug_stream("In write_SetPosZ()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(Spin_motors.SetPosZ_write) ENABLED START -----#
        if self.get_state() == PyTango.DevState.ON:
            self.write("@{} PC={}".format(MOTORS["Z"],str(data))) 
            self.config.set('motor_Z', "position", data)
        else:
            self.connection_warning=True
        #----- PROTECTED REGION END -----#	//	Spin_motors.SetPosZ_write
        
    def read_insert_z_pos(self, attr):
        self.debug_stream("In read_insert_z_pos()")
        #----- PROTECTED REGION ID(Spin_motors.insert_z_pos_read) ENABLED START -----#
        attr.set_value(self.attr_insert_z_pos_read)
        
        #----- PROTECTED REGION END -----#	//	Spin_motors.insert_z_pos_read
        
    def write_insert_z_pos(self, attr):
        self.debug_stream("In write_insert_z_pos()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(Spin_motors.insert_z_pos_write) ENABLED START -----#
        self.attr_insert_z_pos_read=data
        self.config.set('motor_Z', "insert_position", self.attr_insert_z_pos_read)
        #----- PROTECTED REGION END -----#	//	Spin_motors.insert_z_pos_write
        
    def read_retract_z_pos(self, attr):
        self.debug_stream("In read_retract_z_pos()")
        #----- PROTECTED REGION ID(Spin_motors.retract_z_pos_read) ENABLED START -----#
        attr.set_value(self.attr_retract_z_pos_read)
        
        #----- PROTECTED REGION END -----#	//	Spin_motors.retract_z_pos_read
        
    def write_retract_z_pos(self, attr):
        self.debug_stream("In write_retract_z_pos()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(Spin_motors.retract_z_pos_write) ENABLED START -----#
        self.attr_retract_z_pos_read=data
        self.config.set('motor_Z', "retract_position", self.attr_retract_z_pos_read)
        #----- PROTECTED REGION END -----#	//	Spin_motors.retract_z_pos_write
        
    def read_positive_limit_z(self, attr):
        self.debug_stream("In read_positive_limit_z()")
        #----- PROTECTED REGION ID(Spin_motors.positive_limit_z_read) ENABLED START -----#
        attr.set_value(self.attr_positive_limit_z_read)
        
        #----- PROTECTED REGION END -----#	//	Spin_motors.positive_limit_z_read
        
    def read_negative_limit_z(self, attr):
        self.debug_stream("In read_negative_limit_z()")
        #----- PROTECTED REGION ID(Spin_motors.negative_limit_z_read) ENABLED START -----#
        attr.set_value(self.attr_negative_limit_z_read)
        
        #----- PROTECTED REGION END -----#	//	Spin_motors.negative_limit_z_read
        
    def write_connect_via_ethernet(self, attr):
        self.debug_stream("In write_connect_via_ethernet()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(Spin_motors.connect_via_ethernet_write) ENABLED START -----#
        device=str(self)
        device=device[device.index("(")+1:device.index(")")]
        device_server=PyTango.DeviceProxy(device)
        self.connect_via_ehternet=data
        self.config.set('general_settings', "connect_via_ethernet", self.connect_via_ehternet)
        if data==True:
            device_server.write_attribute("connect_via_serial", False)    
        #----- PROTECTED REGION END -----#	//	Spin_motors.connect_via_ethernet_write
        
    def write_connect_via_serial(self, attr):
        self.debug_stream("In write_connect_via_serial()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(Spin_motors.connect_via_serial_write) ENABLED START -----#
        device=str(self)
        device=device[device.index("(")+1:device.index(")")]
        device_server=PyTango.DeviceProxy(device)
        self.connect_via_serial=data
        self.config.set('general_settings', "connect_via_serial", self.connect_via_serial)
        if data==True:
            device_server.write_attribute("connect_via_ethernet", False)
            
        #----- PROTECTED REGION END -----#	//	Spin_motors.connect_via_serial_write
        
    def read_PosX(self, attr):
        self.debug_stream("In read_PosX()")
        #----- PROTECTED REGION ID(Spin_motors.PosX_read) ENABLED START -----#
        attr.set_value(self.attr_PosX_read)
        
        #----- PROTECTED REGION END -----#	//	Spin_motors.PosX_read
        
    def write_StepX(self, attr):
        self.debug_stream("In write_StepX()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(Spin_motors.StepX_write) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	Spin_motors.StepX_write
        
    def write_SpeedX(self, attr):
        self.debug_stream("In write_SpeedX()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(Spin_motors.SpeedX_write) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	Spin_motors.SpeedX_write
        
    def write_StopX(self, attr):
        self.debug_stream("In write_StopX()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(Spin_motors.StopX_write) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	Spin_motors.StopX_write
        
    def write_SetPosX(self, attr):
        self.debug_stream("In write_SetPosX()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(Spin_motors.SetPosX_write) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	Spin_motors.SetPosX_write
        
    def read_positive_limit_XY(self, attr):
        self.debug_stream("In read_positive_limit_XY()")
        #----- PROTECTED REGION ID(Spin_motors.positive_limit_XY_read) ENABLED START -----#
        attr.set_value(self.attr_positive_limit_XY_read)
        
        #----- PROTECTED REGION END -----#	//	Spin_motors.positive_limit_XY_read
        
    def read_negative_limit_XY(self, attr):
        self.debug_stream("In read_negative_limit_XY()")
        #----- PROTECTED REGION ID(Spin_motors.negative_limit_XY_read) ENABLED START -----#
        attr.set_value(self.attr_negative_limit_XY_read)
        
        #----- PROTECTED REGION END -----#	//	Spin_motors.negative_limit_XY_read
        
    def read_PosY(self, attr):
        self.debug_stream("In read_PosY()")
        #----- PROTECTED REGION ID(Spin_motors.PosY_read) ENABLED START -----#
        attr.set_value(self.attr_PosY_read)
        
        #----- PROTECTED REGION END -----#	//	Spin_motors.PosY_read
        
    def write_StepY(self, attr):
        self.debug_stream("In write_StepY()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(Spin_motors.StepY_write) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	Spin_motors.StepY_write
        
    def write_SpeedY(self, attr):
        self.debug_stream("In write_SpeedY()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(Spin_motors.SpeedY_write) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	Spin_motors.SpeedY_write
        
    def write_StopY(self, attr):
        self.debug_stream("In write_StopY()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(Spin_motors.StopY_write) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	Spin_motors.StopY_write
        
    def write_SetPosY(self, attr):
        self.debug_stream("In write_SetPosY()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(Spin_motors.SetPosY_write) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	Spin_motors.SetPosY_write
        
    def read_motor_x_action(self, attr):
        self.debug_stream("In read_motor_x_action()")
        #----- PROTECTED REGION ID(Spin_motors.motor_x_action_read) ENABLED START -----#
        attr.set_value(self.attr_motor_x_action_read)
        
        #----- PROTECTED REGION END -----#	//	Spin_motors.motor_x_action_read
        
    def read_motor_y_action(self, attr):
        self.debug_stream("In read_motor_y_action()")
        #----- PROTECTED REGION ID(Spin_motors.motor_y_action_read) ENABLED START -----#
        attr.set_value(self.attr_motor_y_action_read)
        
        #----- PROTECTED REGION END -----#	//	Spin_motors.motor_y_action_read
        
    def read_motor_z_action(self, attr):
        self.debug_stream("In read_motor_z_action()")
        #----- PROTECTED REGION ID(Spin_motors.motor_z_action_read) ENABLED START -----#
        attr.set_value(self.attr_motor_z_action_read)
        
        #----- PROTECTED REGION END -----#	//	Spin_motors.motor_z_action_read
        
    def read_motor_phi_action(self, attr):
        self.debug_stream("In read_motor_phi_action()")
        #----- PROTECTED REGION ID(Spin_motors.motor_phi_action_read) ENABLED START -----#
        attr.set_value(self.attr_motor_phi_action_read)
        
        #----- PROTECTED REGION END -----#	//	Spin_motors.motor_phi_action_read
        
    def read_motor_theta_action(self, attr):
        self.debug_stream("In read_motor_theta_action()")
        #----- PROTECTED REGION ID(Spin_motors.motor_theta_action_read) ENABLED START -----#
        attr.set_value(self.attr_motor_theta_action_read)
        
        #----- PROTECTED REGION END -----#	//	Spin_motors.motor_theta_action_read
        
    
    
            
    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")
        #----- PROTECTED REGION ID(Spin_motors.read_attr_hardware) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	Spin_motors.read_attr_hardware


    # -------------------------------------------------------------------------
    #    Spin_motors command methods
    # -------------------------------------------------------------------------
    
    def insert(self):
        """ 
        """
        self.debug_stream("In insert()")
        #----- PROTECTED REGION ID(Spin_motors.insert) ENABLED START -----#
        self._insert=True
        #----- PROTECTED REGION END -----#	//	Spin_motors.insert
        
    def retract(self):
        """ 
        """
        self.debug_stream("In retract()")
        #----- PROTECTED REGION ID(Spin_motors.retract) ENABLED START -----#
        self._retract=True
        #----- PROTECTED REGION END -----#	//	Spin_motors.retract
        
    def MoveZ_in(self):
        """ move axis to lower values
        """
        self.debug_stream("In MoveZ_in()")
        #----- PROTECTED REGION ID(Spin_motors.MoveZ_in) ENABLED START -----#
        if self.get_state() == PyTango.DevState.ON:
            if self.attr_PosZ_read-self.stepZ<self.limitZneg:
                self.DIS=self.limitZneg-self.attr_PosZ_read
            else:
                self.DIS=-self.stepZ
            
            self.write('@{} DIS={}'.format(MOTORS["Z"],str(self.DIS)))
            self.write('@{} MI'.format(MOTORS["Z"]))
        else:
            print 1
            self.PosZ_warning=True

        #----- PROTECTED REGION END -----#	//	Spin_motors.MoveZ_in
        
    def MoveZ_out(self):
        """ move axis to higher values
        """
        self.debug_stream("In MoveZ_out()")
        #----- PROTECTED REGION ID(Spin_motors.MoveZ_out) ENABLED START -----#
        if self.get_state() == PyTango.DevState.ON:
            if self.attr_PosZ_read+self.stepZ>self.limitZpos:
                self.DIS=self.limitZpos-self.attr_PosZ_read
            else:
                self.DIS=self.stepZ
            self.write('@{} DIS={}'.format(MOTORS["Z"],str(self.DIS)))
            self.write('@{} MI'.format(MOTORS["Z"]))
        else:
            self.PosZ_warning=True
        #----- PROTECTED REGION END -----#	//	Spin_motors.MoveZ_out
        
    def almclr_z(self):
        """ clear alarm for axis z
        """
        self.debug_stream("In almclr_z()")
        #----- PROTECTED REGION ID(Spin_motors.almclr_z) ENABLED START -----#
        self.write('@{} ALMCLR'.format(MOTORS["Z"]))
        #----- PROTECTED REGION END -----#	//	Spin_motors.almclr_z
        
    def connect(self):
        """ Connect to device
        """
        self.debug_stream("In connect()")
        #----- PROTECTED REGION ID(Spin_motors.connect) ENABLED START -----#
        self.tcp = TCPLink(self.host_ip, self.port)
        self.write('@1ECHO')
        i=0
        while i<10:
            ID=self.write_and_read('@{}ID'.format(str(i)))
            print i
            if ID.find("=")!=-1:
                self.device_id.append(i)
            else:
                pass
            i+=1
        print ("found {} controller(s)".format(str(i)))
        if i!=0:
            self.set_state(PyTango.DevState.ON)
            self.config_load()
        else:
            self.set_state(PyTango.DevState.FAULT)
        
        
        #----- PROTECTED REGION END -----#	//	Spin_motors.connect
        
    def config_save(self):
        """ save the settings of the motors
        """
        self.debug_stream("In config_save()")
        #----- PROTECTED REGION ID(Spin_motors.config_save) ENABLED START -----#       
        with open('settings.ini', 'w') as configfile:
            self.config.write(configfile)
        #----- PROTECTED REGION END -----#	//	Spin_motors.config_save
        
    def config_load(self):
        """ load the settings of the motor
        """
        self.debug_stream("In config_load()")
        #----- PROTECTED REGION ID(Spin_motors.config_load) ENABLED START -----#
        device=str(self)
        device=device[device.index("(")+1:device.index(")")]
        device_server=PyTango.DeviceProxy(device)
        try:
            if "motor_Z" in self.config.sections():
                device_server.write_attribute("retract_z_pos",self.config.getfloat("motor_Z", "retract_position"))
                device_server.write_attribute("insert_z_pos",self.config.getfloat("motor_Z", "insert_position"))
                device_server.write_attribute("StepZ",self.config.getfloat("motor_Z", "step"))
                device_server.write_attribute("SpeedZ",self.config.getfloat("motor_Z", "speed"))
                device_server.write_attribute("SetPosZ",self.config.getfloat("motor_Z", "position"))
            else:
                self.config_file_warning=True
        except:
            self.set_state(PyTango.DevState.FAULT)
            self.config_file_warning=True
        #----- PROTECTED REGION END -----#	//	Spin_motors.config_load
        
    def MoveX_pos(self):
        """ move axis to lower values
        """
        self.debug_stream("In MoveX_pos()")
        #----- PROTECTED REGION ID(Spin_motors.MoveX_pos) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	Spin_motors.MoveX_pos
        
    def MoveX_neg(self):
        """ move axis to lower values
        """
        self.debug_stream("In MoveX_neg()")
        #----- PROTECTED REGION ID(Spin_motors.MoveX_neg) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	Spin_motors.MoveX_neg
        
    def MoveY_pos(self):
        """ move axis to lower values
        """
        self.debug_stream("In MoveY_pos()")
        #----- PROTECTED REGION ID(Spin_motors.MoveY_pos) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	Spin_motors.MoveY_pos
        
    def MoveY_neg(self):
        """ move axis to lower values
        """
        self.debug_stream("In MoveY_neg()")
        #----- PROTECTED REGION ID(Spin_motors.MoveY_neg) ENABLED START -----#
        if self.get_state() == PyTango.DevState.ON:
            if self.attr_PosZ_read-self.stepZ<self.limitZneg:
                self.DIS=self.limitZneg-self.attr_PosZ_read
            else:
                self.DIS=-self.stepZ
            
            self.write('@{} DIS={}'.format(MOTORS["Z"],str(self.DIS)))
            self.write('@{} MI'.format(MOTORS["Z"]))
        else:
            print 1
            self.PosZ_warning=True

        #----- PROTECTED REGION END -----#	//	Spin_motors.MoveY_neg
        
    def almclr_x(self):
        """ clear alarm for axis z
        """
        self.debug_stream("In almclr_x()")
        #----- PROTECTED REGION ID(Spin_motors.almclr_x) ENABLED START -----#
        self.write('@{} ALMCLR'.format(MOTORS["X"]))
        #----- PROTECTED REGION END -----#	//	Spin_motors.almclr_x
        
    def almclr_y(self):
        """ clear alarm for axis z
        """
        self.debug_stream("In almclr_y()")
        #----- PROTECTED REGION ID(Spin_motors.almclr_y) ENABLED START -----#
        self.write('@{} ALMCLR'.format(MOTORS["Y"]))
        #----- PROTECTED REGION END -----#	//	Spin_motors.almclr_y
        
    def StopZ(self):
        """ move axis to lower values
        """
        self.debug_stream("In StopZ()")
        #----- PROTECTED REGION ID(Spin_motors.StopZ) ENABLED START -----#
        if self.get_state() == PyTango.DevState.ON:
            self.write('@{}SSTOP'.format(MOTORS["Z"]))
        #----- PROTECTED REGION END -----#	//	Spin_motors.StopZ
        
    def StopX(self):
        """ move axis to lower values
        """
        self.debug_stream("In StopX()")
        #----- PROTECTED REGION ID(Spin_motors.StopX) ENABLED START -----#
        if self.get_state() == PyTango.DevState.ON:
            self.write('@{}SSTOP'.format(MOTORS["X"]))        
        #----- PROTECTED REGION END -----#	//	Spin_motors.StopX
        
    def StopY(self):
        """ move axis to lower values
        """
        self.debug_stream("In StopY()")
        #----- PROTECTED REGION ID(Spin_motors.StopY) ENABLED START -----#
        if self.get_state() == PyTango.DevState.ON:
            self.write('@{}SSTOP'.format(MOTORS["Y"]))        
        #----- PROTECTED REGION END -----#	//	Spin_motors.StopY
        
    def StopPhi(self):
        """ move axis to lower values
        """
        self.debug_stream("In StopPhi()")
        #----- PROTECTED REGION ID(Spin_motors.StopPhi) ENABLED START -----#
        if self.get_state() == PyTango.DevState.ON:
            self.write('@{}SSTOP'.format(MOTORS["PHI"]))        
        #----- PROTECTED REGION END -----#	//	Spin_motors.StopPhi
        
    def StopTheta(self):
        """ move axis to lower values
        """
        self.debug_stream("In StopTheta()")
        #----- PROTECTED REGION ID(Spin_motors.StopTheta) ENABLED START -----#
        if self.get_state() == PyTango.DevState.ON:
            self.write('@{}SSTOP'.format(MOTORS["THETA"]))    
        #----- PROTECTED REGION END -----#	//	Spin_motors.StopTheta
        
    def StopAll(self):
        """ move axis to lower values
        """
        self.debug_stream("In StopAll()")
        #----- PROTECTED REGION ID(Spin_motors.StopAll) ENABLED START -----#
        if self.get_state() == PyTango.DevState.ON:
            for i in range(len(MOTORS)):
                self.write('@{}SSTOP'.format(str(i)))

        #----- PROTECTED REGION END -----#	//	Spin_motors.StopAll
        
    def almclr_phi(self):
        """ clear alarm for axis z
        """
        self.debug_stream("In almclr_phi()")
        #----- PROTECTED REGION ID(Spin_motors.almclr_phi) ENABLED START -----#
        self.write('@{} ALMCLR'.format(MOTORS["PHI"]))
        #----- PROTECTED REGION END -----#	//	Spin_motors.almclr_phi
        
    def write(self, argin):
        """ write command to motors
        :param argin: 
        :type argin: PyTango.DevString
        """
        self.debug_stream("In write()")
        #----- PROTECTED REGION ID(Spin_motors.write) ENABLED START -----#
        argin=argin+'\r'
        print argin 
        try:
            self.tcp.write(argin)
            time.sleep(0.004)
        except:
            #self.reconnect()
            try:
                self.tcp.write(argin)
                time.sleep(0.004)
            except:
                print('Timeout while writing to "{}"!'.format(type(self).__name__))
                raise        
        #----- PROTECTED REGION END -----#	//	Spin_motors.write
        
    def read(self):
        """ read answers from motors
        :rtype: PyTango.DevString
        """
        self.debug_stream("In read()")
        argout = ""
        #----- PROTECTED REGION ID(Spin_motors.read) ENABLED START -----#
        try:
            time1=time.time()
            argout = self.tcp.read(READ_SIZE,TIMEOUT)
            print "read_time",time.time()-time1
        except:
            print('First reading attempt failed on "{}", trying again...'.format(type(self).__name__))
            try:
                argout = self.tcp.read(READ_SIZE,TIMEOUT)
            except:
                print('Timeout while reading from "{}"!'.format(type(self).__name__))
                raise
        print argout
        argout = argout.replace('\r', '')
        argout = argout.replace('\n', '')
        #----- PROTECTED REGION END -----#	//	Spin_motors.read
        return argout
        
    def write_and_read(self, argin):
        """ 
        :param argin: 
        :type argin: PyTango.DevString
        :rtype: PyTango.DevString
        """
        self.debug_stream("In write_and_read()")
        argout = ""
        #----- PROTECTED REGION ID(Spin_motors.write_and_read) ENABLED START -----#
        self.write(argin)
        argout=self.read()
        #----- PROTECTED REGION END -----#	//	Spin_motors.write_and_read
        return argout
        

    #----- PROTECTED REGION ID(Spin_motors.programmer_methods) ENABLED START -----#
    def read_settings(self):
        pass
            
    def config_check(self):
        if os.path.isfile("settings.ini"):
            self.config.read('settings.ini')
        else:
            self.config_file_warning=True
            return 0
            
    def createReconnectTriggerAttribute(self):
        attr = PyTango.Attr("Reconnect_Trigger", PyTango.DevDouble, PyTango.AttrWriteType.WRITE)
        prop = PyTango.UserDefaultAttrProp()
        prop.set_description("Triggers a reconnection attempt to the hardware.")
        attr.set_default_properties(prop)
        self.add_attribute(attr, self.read_Reconnect_Trigger, self.write_Reconnect_Trigger)

    def read_Reconnect_Trigger(self, attr):
        attr.set_value(0.0)
        
    def write_Reconnect_Trigger(self, attr):
        self.connectToHardware()
    
    def AskQuestion_thread(self):
        while True:
            if self.config_file_warning==True:
                self.config_file_warning=False
                root = tk.Tk()
                root.withdraw()
                MsgBox = tkMessageBox.showinfo ('Warning!','wrong_configuration file',icon = 'warning')
                root.destroy()
            if self.interface_warning==True:
                self.interface_warning=False
                root = tk.Tk()
                root.withdraw()
                MsgBox = tkMessageBox.showinfo ('Warning!','cosse interface for connection',icon = 'warning')
                root.destroy()
            if self.connection_warning==True:
                self.connection_warning=False
                root = tk.Tk()
                root.withdraw()
                MsgBox = tkMessageBox.showinfo ('Warning!','motors are not connected',icon = 'warning')
                root.destroy()
            if self.PosZ_warning==True:
                self.PosZ_warning=False
                root = tk.Tk()
                root.withdraw()
                MsgBox = tkMessageBox.showinfo ('Warning!','Please set position of this axis',icon = 'warning')
                root.destroy()
            if self._insert==True:
                self._insert=False
                root = tk.Tk()
                root.withdraw()
                MsgBox = tkMessageBox.askquestion ('Insert spin filter','You are about to insert spin filter.\r Are you sure? Is valve open?',icon = 'warning')
                if MsgBox == 'yes' and self.attr_motor_z_action_read==False:
                    if self.get_state() == PyTango.DevState.ON:
                        self.write('@{} MA {}'.format(MOTORS["Z"],str(self.attr_insert_z_pos_read)))
                root.destroy()
            if self._retract==True:
                self._insert=False
                root = tk.Tk()
                root.withdraw()
                MsgBox = tkMessageBox.askquestion ('Insert spin filter','You are about to retract spin filter.\r Are you sure?',icon = 'warning')
                if MsgBox == 'yes' and self.attr_motor_z_action_read==False:
                    if self.get_state() == PyTango.DevState.ON:
                        self.write('@{} MA {}'.format(MOTORS["Z"],str(self.attr_retract_z_pos_read)))
                root.destroy()
            time.sleep(0.1)
            
    def pool_motor_variables(self):
        while True:
            if self.get_state() == PyTango.DevState.ON:
                for i in range(0,4,1):
                    PC=self.write_and_read('@'+str(i)+' PC')
                    if PC[0]=='@{} PC'.format(MOTORS["Z"]):
                        val = PC[1].split("=")[1].split(" ")[0]
                        if self.attr_PosZ_read==float(val):
                            self.attr_motor_z_action_read=False
                        else:
                            self.attr_PosZ_read=float(val)
                            self.attr_motor_z_action_read=True
                        print 'motor_{}='.format(_MOTORS[i]),self.attr_PosZ_read
                        self.config.set('motor_{}'.format(_MOTORS[i]), "position", self.attr_PosZ_read)
                for i in range(0,5,1):
                    IO=self.write_and_read('@{} IO'.format(str(i)))
                    if MOTORS["Z"]==str(i):
                        try:
                            if int(IO[6][1])==1:
                                self.attr_positive_limit_z_read=True
                            else:
                                self.attr_positive_limit_z_read=False
                        
                            if int(IO[6][3])==1:
                                self.attr_negative_limit_z_read=True
                            else:
                                self.attr_negative_limit_z_read=False
                        except:
                            print IO
                            pass
                with open('settings.ini', 'w') as configfile:
                    self.config.write(configfile)
                
            else:
                time.sleep(0.1)
    #----- PROTECTED REGION END -----#	//	Spin_motors.programmer_methods

class Spin_motorsClass(PyTango.DeviceClass):
    # -------- Add you global class variables here --------------------------
    #----- PROTECTED REGION ID(Spin_motors.global_class_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	Spin_motors.global_class_variables


    #    Class Properties
    class_property_list = {
        }


    #    Device Properties
    device_property_list = {
        'host_ip':
            [PyTango.DevString, 
             '',
            ["192.168.3.117"] ],
        'port':
            [PyTango.DevLong, 
             '',
            [100]],
        }


    #    Command definitions
    cmd_list = {
        'insert':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'retract':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'MoveZ_in':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'MoveZ_out':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'almclr_z':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'connect':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'config_save':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'config_load':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'MoveX_pos':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'MoveX_neg':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'MoveY_pos':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'MoveY_neg':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'almclr_x':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'almclr_y':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'StopZ':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'StopX':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'StopY':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'StopPhi':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'StopTheta':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'StopAll':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'almclr_phi':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'write':
            [[PyTango.DevString, "none"],
            [PyTango.DevVoid, "none"]],
        'read':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevString, "none"]],
        'write_and_read':
            [[PyTango.DevString, "none"],
            [PyTango.DevString, "none"]],
        }


    #    Attribute definitions
    attr_list = {
        'PosZ':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ],
            {
                'max value': "300",
                'min value': "0",
            } ],
        'StepZ':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.WRITE],
            {
                'max value': "300",
                'min value': "0",
            } ],
        'SpeedZ':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.WRITE],
            {
                'max value': "4",
                'min value': "0",
            } ],
        'StopZ':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.WRITE]],
        'SetPosZ':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.WRITE],
            {
                'max value': "300",
                'min value': "0",
            } ],
        'insert_z_pos':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ_WRITE],
            {
                'max value': "300",
                'min value': "0",
            } ],
        'retract_z_pos':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ_WRITE],
            {
                'unit': "mm",
                'max value': "300",
                'min value': "0",
            } ],
        'positive_limit_z':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.READ]],
        'negative_limit_z':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.READ]],
        'connect_via_ethernet':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.WRITE]],
        'connect_via_serial':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.WRITE]],
        'PosX':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ],
            {
                'max value': "12.5",
                'min value': "-12.5",
            } ],
        'StepX':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.WRITE],
            {
                'max value': "8",
                'min value': "0",
            } ],
        'SpeedX':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.WRITE]],
        'StopX':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.WRITE]],
        'SetPosX':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.WRITE]],
        'positive_limit_XY':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.READ]],
        'negative_limit_XY':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.READ]],
        'PosY':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ],
            {
                'max value': "12.5",
                'min value': "-12.5",
            } ],
        'StepY':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.WRITE]],
        'SpeedY':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.WRITE]],
        'StopY':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.WRITE]],
        'SetPosY':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.WRITE]],
        'motor_x_action':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.READ]],
        'motor_y_action':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.READ]],
        'motor_z_action':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.READ]],
        'motor_phi_action':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.READ]],
        'motor_theta_action':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.READ]],
        }


def main():
    try:
        py = PyTango.Util(sys.argv)
        py.add_class(Spin_motorsClass, Spin_motors, 'Spin_motors')
        #----- PROTECTED REGION ID(Spin_motors.add_classes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	Spin_motors.add_classes

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed as e:
        print ('-------> Received a DevFailed exception:', e)
    except Exception as e:
        print ('-------> An unforeseen exception occured....', e)

if __name__ == '__main__':
    main()
